version: "3.8"

services:
  backend:
    build: .
    container_name: brief_bot
    restart: always
    env_file:
      - .env
    depends_on: &depends_on
      - db
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ulimits: &ulimits
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000


  db:
    image:  postgres:15.3-alpine
    container_name: brief_db
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - ./.storages/postgresdata:/var/lib/postgresql/data
    logging: *logging
    env_file:
      - .env
